import { useState } from "react";
import { jsPDF } from "jspdf";

function exportPDF(data, meta = {}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const maxWidth = pageWidth - margin * 2;
  let y = 22;

  const ensureSpace = (needed = 12) => {
    if (y + needed > 280) {
      doc.addPage();
      y = 22;
    }
  };

  const line = (text, opts = {}) => {
    const {
      size = 10,
      style = "normal",
      color = [51, 65, 85],
      gap = 6,
      indent = 0,
    } = opts;
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(String(text || ""), maxWidth - indent);
    ensureSpace(lines.length * (size * 0.45) + gap);
    doc.text(lines, margin + indent, y);
    y += lines.length * (size * 0.45) + gap;
  };

  const section = (title) => {
    ensureSpace(16);
    y += 4;
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.6);
    doc.line(margin, y - 4, margin + 28, y - 4);
    line(title, { size: 13, style: "bold", color: [30, 27, 75], gap: 8 });
  };

  // Header
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 36, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("AI Startup Validator", margin, 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Validation Report", margin, 26);
  y = 48;

  if (meta.idea) {
    line("Startup Idea", { size: 9, style: "bold", color: [100, 116, 139], gap: 3 });
    line(meta.idea, { size: 11, style: "bold", color: [15, 23, 42], gap: 8 });
  }

  const metaBits = [
    meta.industry && `Industry: ${meta.industry}`,
    meta.audience && `Audience: ${meta.audience}`,
    meta.country && `Market: ${meta.country}`,
    meta.budget && `Budget: ${meta.budget}`,
  ].filter(Boolean);
  if (metaBits.length) {
    line(metaBits.join("  ·  "), { size: 9, color: [100, 116, 139], gap: 10 });
  }

  section("Score Overview");
  line(`Score: ${data.score} / 10`, { size: 14, style: "bold", color: [79, 70, 229], gap: 5 });
  line(`Success Chance: ${data.successChance}`, { size: 11, gap: 5 });
  line(data.marketDemand, { size: 10, color: [71, 85, 105], gap: 6 });

  if (data.competitors?.length) {
    section("Competitors");
    data.competitors.forEach((c, i) => line(`${i + 1}. ${c}`, { indent: 4, gap: 4 }));
  }

  if (data.swot) {
    section("SWOT Analysis");
    [
      ["Strengths", data.swot.strengths],
      ["Weaknesses", data.swot.weaknesses],
      ["Opportunities", data.swot.opportunities],
      ["Threats", data.swot.threats],
    ].forEach(([title, items]) => {
      line(title, { size: 11, style: "bold", color: [67, 56, 202], gap: 4 });
      (items || []).forEach((item) => line(`• ${item}`, { indent: 4, gap: 3.5 }));
      y += 2;
    });
  }

  if (data.revenueModels?.length) {
    section("Revenue Models");
    data.revenueModels.forEach((r, i) => line(`${i + 1}. ${r}`, { indent: 4, gap: 4 }));
  }

  if (data.suggestions?.length) {
    section("AI Suggestions");
    data.suggestions.forEach((s, i) => line(`${i + 1}. ${s}`, { indent: 4, gap: 4 }));
  }

  ensureSpace(16);
  y += 8;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  line(
    `Generated by AI Startup Validator · ${new Date().toLocaleDateString()}`,
    { size: 8, color: [148, 163, 184], gap: 0 }
  );

  const filename = `startup-report-${(meta.idea || "idea").slice(0, 24).replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "export"}.pdf`;
  doc.save(filename);
}

export default function Report({ data, meta = {}, reportId, onViewShared }) {
  const [copied, setCopied] = useState(false);
  const [sharing, setSharing] = useState(false);

  const scoreColor =
    data.score >= 7
      ? "text-emerald-500"
      : data.score >= 5
        ? "text-amber-500"
        : "text-red-500";

  const chanceBg =
    data.successChance === "High"
      ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300"
      : data.successChance === "Medium"
        ? "bg-amber-100 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300"
        : "bg-red-100 text-red-700 dark:bg-red-950/60 dark:text-red-300";

  const handleShare = async () => {
    if (!reportId) return;
    const url = `${window.location.origin}/report/${reportId}`;
    setSharing(true);
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      window.prompt("Copy this share link:", url);
    } finally {
      setSharing(false);
    }
  };

  return (
    <div className="w-full max-w-5xl mx-auto mt-8 space-y-5 animate-slide-up">
      {/* Actions */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="font-display text-lg font-semibold text-slate-900 dark:text-white">
          Validation Report
        </h2>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => exportPDF(data, meta)}
            className="btn-secondary inline-flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </button>
          <button
            type="button"
            onClick={handleShare}
            disabled={!reportId || sharing}
            title={reportId ? "Copy shareable link" : "Save report first to share"}
            className="btn-ghost inline-flex items-center gap-2 disabled:opacity-50"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
            </svg>
            {copied ? "Link copied!" : "Share Report"}
          </button>
        </div>
      </div>

      {/* Score Card */}
      <div className="card p-6 sm:p-10 text-center relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/80 via-transparent to-violet-50/40 dark:from-indigo-950/40 dark:to-violet-950/20 pointer-events-none" />
        <div className="relative">
          <p className="text-slate-400 dark:text-slate-500 text-sm font-medium mb-2 tracking-wide uppercase">
            Startup Score
          </p>
          <p className={`font-display text-6xl sm:text-7xl font-extrabold ${scoreColor} tabular-nums`}>
            {data.score}
          </p>
          <p className="text-slate-400 dark:text-slate-500 text-sm mt-1">out of 10</p>
          <span className={`inline-block mt-5 px-4 py-1.5 rounded-full text-sm font-semibold ${chanceBg}`}>
            {data.successChance} Success Chance
          </span>
          <p className="text-slate-600 dark:text-slate-300 text-sm mt-5 max-w-lg mx-auto leading-relaxed">
            {data.marketDemand}
          </p>
        </div>
      </div>

      {/* Competitors */}
      <div className="card card-hover p-5 sm:p-6">
        <h3 className="font-display text-base font-semibold text-slate-800 dark:text-slate-100 mb-4">
          Competitors
        </h3>
        <div className="flex flex-wrap gap-2">
          {(data.competitors || []).map((c, i) => (
            <span
              key={i}
              className="bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 px-3.5 py-1.5 rounded-full text-sm font-medium transition-colors hover:bg-indigo-50 hover:text-indigo-700 dark:hover:bg-indigo-950/50 dark:hover:text-indigo-300"
            >
              {c}
            </span>
          ))}
        </div>
      </div>

      {/* SWOT */}
      <div className="card p-5 sm:p-6">
        <h3 className="font-display text-base font-semibold text-slate-800 dark:text-slate-100 mb-4">
          SWOT Analysis
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
          <div className="bg-emerald-50 dark:bg-emerald-950/40 rounded-xl p-4 border border-emerald-100/80 dark:border-emerald-900/50 transition-transform hover:scale-[1.01]">
            <p className="text-emerald-700 dark:text-emerald-400 font-semibold text-sm mb-2">Strengths</p>
            <ul className="space-y-1.5">
              {(data.swot?.strengths || []).map((s, i) => (
                <li key={i} className="text-emerald-700/80 dark:text-emerald-300/80 text-sm leading-snug">• {s}</li>
              ))}
            </ul>
          </div>
          <div className="bg-red-50 dark:bg-red-950/40 rounded-xl p-4 border border-red-100/80 dark:border-red-900/50 transition-transform hover:scale-[1.01]">
            <p className="text-red-700 dark:text-red-400 font-semibold text-sm mb-2">Weaknesses</p>
            <ul className="space-y-1.5">
              {(data.swot?.weaknesses || []).map((s, i) => (
                <li key={i} className="text-red-700/80 dark:text-red-300/80 text-sm leading-snug">• {s}</li>
              ))}
            </ul>
          </div>
          <div className="bg-sky-50 dark:bg-sky-950/40 rounded-xl p-4 border border-sky-100/80 dark:border-sky-900/50 transition-transform hover:scale-[1.01]">
            <p className="text-sky-700 dark:text-sky-400 font-semibold text-sm mb-2">Opportunities</p>
            <ul className="space-y-1.5">
              {(data.swot?.opportunities || []).map((s, i) => (
                <li key={i} className="text-sky-700/80 dark:text-sky-300/80 text-sm leading-snug">• {s}</li>
              ))}
            </ul>
          </div>
          <div className="bg-amber-50 dark:bg-amber-950/40 rounded-xl p-4 border border-amber-100/80 dark:border-amber-900/50 transition-transform hover:scale-[1.01]">
            <p className="text-amber-700 dark:text-amber-400 font-semibold text-sm mb-2">Threats</p>
            <ul className="space-y-1.5">
              {(data.swot?.threats || []).map((s, i) => (
                <li key={i} className="text-amber-700/80 dark:text-amber-300/80 text-sm leading-snug">• {s}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Revenue Models */}
      <div className="card card-hover p-5 sm:p-6">
        <h3 className="font-display text-base font-semibold text-slate-800 dark:text-slate-100 mb-4">
          Revenue Models
        </h3>
        <div className="space-y-2">
          {(data.revenueModels || []).map((r, i) => (
            <div
              key={i}
              className="flex items-center gap-3 bg-indigo-50 dark:bg-indigo-950/40 rounded-xl px-4 py-3 border border-indigo-100/60 dark:border-indigo-900/40 transition-colors hover:bg-indigo-100/80 dark:hover:bg-indigo-950/60"
            >
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-indigo-600 text-white text-xs font-bold">
                {i + 1}
              </span>
              <span className="text-indigo-800 dark:text-indigo-200 text-sm font-medium">{r}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Suggestions */}
      <div className="card card-hover p-5 sm:p-6">
        <h3 className="font-display text-base font-semibold text-slate-800 dark:text-slate-100 mb-4">
          AI Suggestions
        </h3>
        <div className="space-y-2">
          {(data.suggestions || []).map((s, i) => (
            <div
              key={i}
              className="flex items-start gap-3 bg-slate-50 dark:bg-slate-800/50 rounded-xl px-4 py-3 border border-slate-100 dark:border-slate-800 transition-colors hover:border-indigo-200 dark:hover:border-indigo-800"
            >
              <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-indigo-100 dark:bg-indigo-900/50 text-indigo-600 dark:text-indigo-300 text-xs font-bold">
                {i + 1}
              </span>
              <span className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed">{s}</span>
            </div>
          ))}
        </div>
      </div>

      {onViewShared && reportId && (
        <p className="text-center text-xs text-slate-400 dark:text-slate-500 pb-2">
          Shareable at{" "}
          <button
            type="button"
            onClick={onViewShared}
            className="text-indigo-500 hover:underline"
          >
            /report/{reportId}
          </button>
        </p>
      )}
    </div>
  );
}
